### ISSUE TITLE
Uang malam belum termasuk administrasi.

### ISSUE THREAD

**Issue by CyberKasumi** [CyberKasumi/KGAM#2]
Daily report does not include admin.
Would like to have admin fee included.

**Comment by IvanHalimP** [comment]
It was never exist
Uang malam itu casenya gimana?
Daily report... ini kyknya bgian u...

**Comment by CyberKasumi** [comment]
never exist tho.
uang malam itu daily report :)) digenerate tiap mau tutup klinik

**Comment by IvanHalimP** [comment]
uang malam brp duit?
tinggal masukin ke DB ato gmn?

**Comment by CyberKasumi** [comment]
bad news... we didn't include this in DB it seems...

**Comment by CyberKasumi** [comment]
eh ada ding

**Comment by IvanHalimP** [comment]
1. me baru tau ini ada taun ini
2. me gatau berapa
3. me gatau itungan gimana. apakah fixed atau ada komponen yg mesti diitung lagi.

seriously...
