### ISSUE TITLE
Kalo mau DP masukinnya gimana?

### ISSUE THREAD

**Issue by CyberKasumi** [CyberKasumi/KGAM#4]
How to input DP?

Current: it's supposed to be inputted directly if it's creditable

let's just investigate this first and see if it's working

**Comment by IvanHalimP** [comment]
Have explained how the program works?

**Comment by CyberKasumi** [comment]
probably they forgot.. or there might be something faulty in the program copied there

**Comment by CyberKasumi** [comment]
yup, faulty when it is inputted by typing txtTreatmentId
