### ISSUE TITLE
Rontgen haven't been added

### ISSUE THREAD

**Issue by CyberKasumi** [CyberKasumi/KGAM#5]
Lap rontgen masuknya kemana? Untuk adm sama rontgen itu nanti pemasukan untuk klinik.

**Comment by IvanHalimP** [comment]
hmmm
lab? dunno
me ga gitu ngerti business processnya
cashflownya juga me ga terlalu ngerti selain dari yang me baca dari sample reports sama bon yang dikasi

**Comment by IvanHalimP** [comment]
dan itungannya gimana
