### ISSUE TITLE
Supplier pembelian alat2 dan bahan2 minta di input juga

### ISSUE THREAD

**Issue by CyberKasumi** [CyberKasumi/KGAM#7]
Supplier pembelian alat2 dan bahan2 minta di input juga ( termasuk data kapan datang, sudah dibayar atau belum )

probs this is new feature.. see if we can do this... but don't force if we can't

**Comment by IvanHalimP** [comment]
alat dan bahan...
dia maunya gimana dulu...
trus urusan sama report integrationnya gimana.
report masuk kemana?

**Comment by CyberKasumi** [comment]
ini mereka baru minta kykny :/
this will be done later if we got time

**Comment by CyberKasumi** [comment]
[Supplier.xlsx](https://github.com/CyberKasumi/KGAM/files/835638/Supplier.xlsx)

**Comment by IvanHalimP** [comment]
Tanggal itu tanggal apa?
Pelunasan isinya apaan?

Terus nyicil? apa lsg lunas?
apa gmn?

**Comment by CyberKasumi** [comment]
tanggal itu tanggal invoice
Pelunasan itu isinya 'cash' ato 'transfer'
keterangan itu kyk, udah lunas apa blom, dan kalo udah itu tanggal berapa lunasnya

ktny works only as reminder
